# Generated by Django 4.1.3 on 2024-10-12 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('product_qty', models.IntegerField(max_length=10)),
                ('unit_price', models.IntegerField(max_length=20)),
                ('product_status', models.BooleanField(default=True)),
            ],
        ),
    ]
