# Generated by Django 4.1.3 on 2024-11-01 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_product_cart_product_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_cart',
            name='product_total',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
