# Generated by Django 5.0.1 on 2024-11-07 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_product_cart_product_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_cart',
            name='product_total',
        ),
    ]
