# Generated by Django 4.1.3 on 2024-11-07 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_shipment_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='address1',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='address2',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='landmark',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='mobile',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='pincode',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='state',
            field=models.CharField(max_length=50),
        ),
    ]
